replicaCount: 8

image:
  repository: <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/sample-test
  tag: latest

service:
  type: LoadBalancer
  port: 8080

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"

  limits:
    cpu: "500m"
    memory: "512Mi"

autoscaling:
  minReplicas: 8
  maxReplicas: 15
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 60