- name: package modules
  hosts: all
  become: true
  tasks: 
  - name: install apache2
    package:
      name: apache2
      update_cache: yes
      state: present
    when: ansible_os_family == "Debian"
  
  - name: copy index.html from local to webserver
    copy:
      src: index.html
      dest: /var/www/html/index.html
      mode: '0644'
 
  - name: add line in index.html
    lineinfile:
      path: /var/www/html/index.html
      regexp: '^</h1>'
      line: '<h1> hello this is new line added </h1>'

  - name: add lines in index.html
    blockinfile:
      path: /var/www/html/index.html
      block: |
        <h1> hello my name is suraj </h1>
        <h2> this line 2 </h2>
        <h3> this is block of lines </h3>

  - name: start apache2
    systemd: 
      name: apache2
      state: restarted
      enabled: true