- name: file to do multipal work/install
  hosts: all
  tasks:
    - name: print multipal items
      debug:
        msg: "{{item}}"
      loop:
       - hello
       - how are you?
       - i am good.
