- name: my 1st playbook
  hosts: all
  vars:
    animal: "tiger"
  vars_files:
    - ./var.txt
  tasks:
    - name: print animal1
      debug:
        msg: "hello I am {{animal}}"
    - name: print animal2
      debug:
        msg: "hello I am {{animal}}"
      vars:
        animal: "lion"
    - name: print animal3
      debug:
        msg: "hello I am {{animal}}"



#global
#local