- name: my 1st playbook
  hosts: all
  vars:
    animal: "tiger"
  tasks:
    - name: print tiger
      debug:
        msg: "hello I am {{animal}}"
    - name: print tiger2
      debug:
        msg: "hello I am {{animal}}"



#global
#local